<?php /* @var $meetings \Application\Collection\MeetingCollection */ ?>
<h1>Meetings</h1>
<ul>
    <?php foreach ($meetings as $meeting) : /* @var $meeting \Application\Entity\Meeting */ ?>
        <li>
            <a href="meeting/<?= urlencode($meeting->getId()) ?>">
                <?= $meeting->getName(); ?>
            </a>

            <p><a href="delete/<?= urlencode($meeting->getId()) ?>">[ Supprimer ]</a></p>
        </li>

    <?php endforeach ?>
</ul>